version: "3.3"
services:
  instagram-rest-api:
    image: cr.dotdevio.com/anonstory/instagrapi-rest:latest
    build: .
    stdin_open: true
    tty: true
    #ports:
    #  - "8090:8000"
    volumes:
      - .:/app
